#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "Nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    guifont = "FuraCode Nerd Font Mono Retina:h15"
    filetree_direction = "left"
    automatic_update = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
  name = "ui"

[[layers]]
name = "denite"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#c"

[[layers]]
name = "format"

[[layers]]
name = "incsearch"

[[layers]]
  name = "ui"
  enable_sidebar = true

[[custom_plugins]]
  name = "rakr/vim-two-firewatch"
  merged = 0

[[custom_plugins]]
  name = "arcticicestudio/nord-vim"
  merged = 0

[[custom_plugins]]
  name = "dylanaraps/wal.vim"
  merged = 0

[[custom_plugins]]
  name = "glacambre/firenvim"
  merged = 0
  
[[custom_plugins]]
  name = "tpope/vim-surround"
  merged = 0

[[custom_plugins]]
  name = "lervag/vimtex"
  merged = 0
  
[[custom_plugins]]
  name = "xuhdev/vim-latex-live-preview"
  merged = 0
